# Generated by Django 3.0.5 on 2020-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('bid', models.FloatField()),
            ],
        ),
    ]
