# Generated by Django 3.0.5 on 2020-11-08 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 11, 9)),
        ),
    ]
