# Generated by Django 3.0.5 on 2020-11-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201109_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='long_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
