# Generated by Django 3.0.5 on 2020-11-13 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201113_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 31, 35, 847197)),
        ),
    ]
