# Generated by Django 3.0.5 on 2020-11-13 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201113_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cat',
        ),
        migrations.AddField(
            model_name='listing',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='category', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 58, 52, 351347)),
        ),
    ]
