# Generated by Django 3.0.5 on 2020-11-19 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201118_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cat',
        ),
        migrations.AddField(
            model_name='listing',
            name='cats',
            field=models.ManyToManyField(blank=True, to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 13, 40, 144907)),
        ),
    ]
