# Generated by Django 3.0.5 on 2020-11-19 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20201119_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 28, 37, 190476)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
