# Generated by Django 3.0.5 on 2020-11-20 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201121_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 7, 18, 693928)),
        ),
    ]
