# Generated by Django 3.0.5 on 2020-11-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201121_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 16, 27, 49, 143032)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added',
            field=models.IntegerField(default=0),
        ),
    ]
