# Generated by Django 3.0.5 on 2020-11-21 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201121_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cats',
        ),
        migrations.AddField(
            model_name='listing',
            name='cats',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 38, 58, 240526)),
        ),
    ]
