# Generated by Django 3.0.5 on 2020-11-21 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20201122_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 1, 31, 22, 39302)),
        ),
    ]
