# Generated by Django 3.0.5 on 2020-11-21 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20201122_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 1, 33, 45, 806910)),
        ),
    ]
