# Generated by Django 3.0.5 on 2020-11-21 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20201122_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='latest_price',
            new_name='current_price',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 1, 39, 42, 539381)),
        ),
    ]
