# Generated by Django 3.0.5 on 2020-11-27 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20201123_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 23, 56, 54, 341336)),
        ),
    ]
