# Generated by Django 3.0.5 on 2020-11-28 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20201128_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cm_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 23, 4, 50, 540430)),
        ),
    ]
