# Generated by Django 3.0.5 on 2020-11-28 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20201129_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cm_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 53, 28, 920751)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 53, 28, 919753)),
        ),
    ]
