# Generated by Django 3.0.5 on 2020-11-28 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20201129_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cm_time',
            field=models.DateField(default=datetime.date(2020, 11, 29)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 54, 38, 791455)),
        ),
    ]
