# Generated by Django 3.0.5 on 2020-11-28 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20201129_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cm_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 55, 8, 113770)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 0, 55, 8, 112772)),
        ),
    ]
