# Generated by Django 3.0.5 on 2020-11-29 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20201129_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cm_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 20, 2, 25, 626167)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 20, 2, 25, 625170)),
        ),
    ]
